on:
  push:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello"
  
  Docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  startup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  setup:
    needs: [ build, Docker, startup ]
    uses: ./.github/workflows/setup.yaml  # Reusable workflow

  checkov: 
    needs: setup
    runs-on: ubuntu-latest  
    steps:
      - run: echo "hello"
      
  plan:
    needs: checkov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Terraform  # Install Terraform again in the plan job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify version if necessary

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test.tf  # Download artifact from the previous setup step

      - run: terraform init  # Terraform is now available

  apply: 
    needs: plan
    runs-on: ubuntu-latest 
    steps:
      - name: Set up Terraform  # Install Terraform again in the apply job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify version if necessary

      - run: echo ${{ matrix.envi }}  # Now Terraform is installed in this job as well

  trivy: 
    needs: [ Docker, setup ]
    runs-on: ubuntu-latest  
    steps:  
      - name: Install Trivy  # Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y trivy  # Install the Trivy tool

      - name: Run Trivy scan
        run: trivy --version  # Optionally, print Trivy version
        # Add the specific Trivy scan command you want to run here
        # Example: trivy image <image-name> or trivy filesystem <path>
      
  Dockerise: 
    needs: trivy
    runs-on: ubuntu-latest  
    steps:  
      - run: echo "hello"
