on:
  push:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello"
      
  Docker:  # Move Docker before setup, since it's needed in setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  startup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  setup:
    needs: [ build, Docker, startup ]
    uses: ./.github/workflows/setup.yaml  # Ensure this reusable workflow exists

  checkov: 
    needs: setup
    runs-on: ubuntu-latest  
    steps:
      - run: echo "hello"
      
  plan:
    needs: checkov
    if: success()
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        envi: [dev, stage, prod]  # Corrected variable name
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test.tf  # Make sure this artifact exists from a previous step
      - run: terraform init  # Ensure correct directory if needed

  apply: 
    needs: plan
    if: success()
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false
      matrix:
        envi: [dev, stage, prod]  # Corrected variable name
    steps:
      - run: echo ${{ matrix.envi }}  # Make sure to reference correct matrix variable
      
  trivy: 
    needs: [ Docker, setup ]
    runs-on: ubuntu-latest  
    steps:  
      - run: echo "hello"
      
  Dockerise: 
    needs: trivy
    runs-on: ubuntu-latest  
    steps:  
      - run: echo "hello"
