on:
  push:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello"
      
  startup:
    needs: [ build, Docker ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  setup:
    needs: [ build, Docker, startup ]
    uses: ./.github/workflows/setup.yaml  # Ensure this path is correct for reusable workflow
      
  checkov: 
    needs: setup
    runs-on: ubuntu-latest  
    steps:
      - run: echo "hello"
      
  plan:
    needs: checkov
    if: success()
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        envi: [dev, stage, prod]  # Corrected variable name
    steps:
      - run: echo ${{ matrix.envi }}  # Corrected variable reference
      
  apply: 
    needs: plan
    if: success()
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false
      matrix:
        envi: [dev, stage, prod]  # Corrected variable name
    steps:
      - run: echo ${{ matrix.envi }}  # Corrected variable reference
      
  Docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  trivy: 
    needs: [ Docker, setup ]
    runs-on: ubuntu-latest  
    steps:  
      - run: echo "hello"
      
  Dockerise: 
    needs: trivy
    runs-on: ubuntu-latest  
    steps:  
      - run: echo "hello"
