on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello"  # Simple step in the build job
  
  Docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"  # Simple step in the Docker job
      
  startup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"  # Simple step in the startup job

  setup:  # Use setup.yaml to install and initialize Terraform
    needs: [build, Docker, startup]
    uses: ./.github/workflows/setup.yaml  # Calls the reusable workflow to install and initialize Terraform

  checkov: 
    needs: setup  # Depends on the setup job, so it will run after setup completes
    runs-on: ubuntu-latest  
    steps:
      - name: Run Terraform formatting check
        run: terraform fmt -check  # Check if the Terraform files are formatted correctly

  plan:
    needs: checkov 
    if: success() # Depends on the checkov job, so it will run after checkov completes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envi: [ dev, stage, pro ]
    steps:
      - name: Download Terraform artifact
        uses: actions/download-artifact@v4
        with:
           name: test.tf
      - name: intialize terraform
        run: terraform init
      - name: Plan Terraform changes
        run: terraform plan  # Runs Terraform plan to check infrastructure changes

  apply: 
    needs: plan  # Depends on the plan job, so it will run after plan completes
    runs-on: ubuntu-latest 
    steps:
      - name: Download Terraform artifact
        uses: actions/download-artifact@v4
        with:
           name: test.tf   
      - name: Apply Terraform changes
        run: terraform apply -auto-approve  # Apply Terraform changes without manual approval

  trivy: 
    needs: [Docker, setup]  # Depends on Docker and setup jobs
    runs-on: ubuntu-latest  
    steps:  
      - name: Install and Run Trivy
        run: echo "Running Trivy scan here"  # Placeholder for the Trivy scan

  Dockerise: 
    needs: trivy  # Depends on the trivy job, so it will run after trivy completes
    runs-on: ubuntu-latest  
    steps:  
      - run: echo "Dockerization step here"  # Placeholder for the Dockerization step
