name: setup

on:
  workflow_call
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      - name: initialize Terraform
        run: terraform init
      - name: upload
        uses: actions/upload-artifact@v4
        with: 
           name: test.tf
           path: ./.test.tf
